spring:
  application:
    name: SKube
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/skube
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/skube
    user: postgres
    password: password
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET:LXEgAPZGrj52xr8xqn5CJuCqXhBaWbpo66nv7Imw6Y1P51GNFcw437tHgi5TuVariEJ4HaxEqYQ/Q2PHl+B0FA==}
    expiration: ${JWT_EXPIRATION:86400000}

